---
- name: Check if honeyd already is installed
  stat: path=/usr/bin/honeyd
  register: honeyd_installed

- name: Running apt-get update
  when: honeyd_installed.stat.exists == False
  apt: update_cache=yes

- name: Install honeyd dependencies for Ubuntu
  when: honeyd_installed.stat.exists == False
  apt: name={{ item }} state=present
  with_items:
    - automake
    - bison
    - build-essential
    - farpd
    - flex
    - gcc
    - git
    - htop
    - libdumbnet-dev
    - libedit-dev
    - libevent-dev
    - libpcap-dev
    - libpcre3-dev
    - libtool
    - make
    - moreutils
    - nmap
    - p0f
    - python
    - vim
    - zlib1g-dev
  when:
    ansible_distribution == "Ubuntu"


